#!/usr/bin/env bash

RESET="\e[0m"
RED="\e[1;31m"

has_installed() {
    if ! which "$1" > /dev/null; then
        echo -e "${RED}$1 is not installed${RESET}"
        exit 1
    fi
}

has_installed youtube-dl
has_installed ffmpeg

youtube-dl --ignore-errors --format bestaudio --extract-audio --audio-format mp3 --output "%(title)s.%(ext)s" --yes-playlist "$1"
