#!/usr/bin/env python3

import argparse
import os
import xml.etree.ElementTree as ET

parser = argparse.ArgumentParser(description="Update WebStorm prettier patterns")
parser.add_argument(
    "--file", "-f", type=str, help="Absolute path to .idea/prettier.xml file"
)
parser.add_argument(
    "pattern", type=str, help="Glob pattern for prettier to format files with"
)


def main():
    args = parser.parse_args()

    filename = args.file
    new_pattern = args.pattern

    os.system(f"cp {filename} {filename}.bak")

    tree = ET.parse(filename)
    root = tree.getroot()

    for option in root.iter("option"):
        if option.attrib.get("name") == "myFilesPattern":
            option.set("value", new_pattern)

    tree.write(filename, encoding="UTF-8", xml_declaration=True)


if __name__ == "__main__":
    main()
