#!/usr/bin/env bash

set -euo pipefail

# DOCS:
# - https://askubuntu.com/a/1475182
# - https://fedoramagazine.org/automatically-decrypt-your-disk-using-tpm2/
# - https://github.com/latchset/clevis
# - https://wiki.archlinux.org/title/Clevis
# - https://wiki.archlinux.org/title/Trusted_Platform_Module

if ! command -v clevis >/dev/null 2>&1; then
    echo "Missing clevis package"
    exit 1
fi

if [[ -z $1 ]]; then
    echo "Missing LUKS device path (e.g /dev/nvme0n1p3)"
    exit 1
fi

LUKS_DEVICE=$1

echo -e "\nList pins for LUKS device $LUKS_DEVICE"
sudo clevis luks list -d "$LUKS_DEVICE"


echo -en "\nSelect pin id to update: "
read PIN_ID

echo -n "Enter boot passphrase password: "
read -s BOOT_PASSPHRASE

sudo clevis luks regen -q -d "$LUKS_DEVICE" -s "$PIN_ID" tpm2  <<< "$BOOT_PASSPHRASE"

echo -e "\nUpdating initramfs to allow automatic decryption on boot"
sudo update-initramfs -u -k all

