#!/usr/bin/env python3

from installer import Package, create_installer

create_installer("editors", [
    Package("vim", "sudo apt install -y vim"),
    Package("vscode", "sudo snap install code --classic"),
    Package("rider", "sudo snap install rider --classic")
])()
