#!/usr/bin/env python3

from installer import Package, create_installer, join

FIRACODE_NERD_TMP='/tmp/firacode-nerd'
FIRACODE_NERD_TMP_ZIP='/tmp/FiraCode.zip'
INSTALL_FIRACODE_NERD = [
    f'dra download -s FiraCode.zip -o {FIRACODE_NERD_TMP_ZIP} ryanoasis/nerd-fonts',
    f'mkdir -p {FIRACODE_NERD_TMP}',
    f'unzip {FIRACODE_NERD_TMP_ZIP} -d {FIRACODE_NERD_TMP}',
    'mkdir -p ~/.fonts',
    f"mv '{FIRACODE_NERD_TMP}/FiraCodeNerdFont-Light.ttf' ~/.fonts",
    f"mv '{FIRACODE_NERD_TMP}/FiraCodeNerdFont-Medium.ttf' ~/.fonts",
    f"mv '{FIRACODE_NERD_TMP}/FiraCodeNerdFont-Regular.ttf' ~/.fonts",
    f"mv '{FIRACODE_NERD_TMP}/FiraCodeNerdFont-Bold.ttf' ~/.fonts",
    f"mv '{FIRACODE_NERD_TMP}/FiraCodeNerdFont-SemiBold.ttf' ~/.fonts",
    'fc-cache -f -v',
]

create_installer("fonts", [
    Package("firacode", "sudo apt install -y fonts-firacode"),
    Package("firacode-nerd", join(INSTALL_FIRACODE_NERD)),
])()
