#!/usr/bin/env python3

from installer import Package, create_installer, join

FIRACODE_NERD_TMP='/tmp/firacode-nerd'
INSTALL_FIRACODE_NERD = [
    'dra download -s FiraCode.zip ryanoasis/nerd-fonts',
    f'mkdir -p {FIRACODE_NERD_TMP}',
    f'unzip FiraCode.zip -d {FIRACODE_NERD_TMP}',
    'mkdir -p ~/.fonts',
    f"mv '{FIRACODE_NERD_TMP}/Fira Code Light Nerd Font Complete.ttf' ~/.fonts",
    f"mv '{FIRACODE_NERD_TMP}/Fira Code Medium Nerd Font Complete.ttf' ~/.fonts",
    f"mv '{FIRACODE_NERD_TMP}/Fira Code Regular Nerd Font Complete.ttf' ~/.fonts",
    f"mv '{FIRACODE_NERD_TMP}/Fira Code Bold Nerd Font Complete.ttf' ~/.fonts",
    f"mv '{FIRACODE_NERD_TMP}/Fira Code SemiBold Nerd Font Complete.ttf' ~/.fonts",
    'fc-cache -f -v',
]

create_installer("fonts", [
    Package("firacode", "sudo apt install -y fonts-firacode"),
    Package("firacode-nerd", join(INSTALL_FIRACODE_NERD)),
])()
