#!/usr/bin/env python3

from installer import Package, installer

installer(
    "gnome",
    [
        Package("tweaks", "sudo apt install -y gnome-tweaks"),
        Package("scanner", "sudo apt install -y simple-scan"),
        Package("weather", "sudo apt install -y gnome-weather"),
    ],
)
