#!/usr/bin/env python3

from installer import Package, create_installer

create_installer("misc", [
    Package("postman", "flatpak install -y flathub com.getpostman.Postman"),
    Package("gimp", "sudo snap install gimp"),
    Package("vlc", "sudo snap install vlc"),
    Package("peek", "flatpak install -y flathub com.uploadedlobster.peek"),
])()
