#!/usr/bin/env python3

from installer import Package, bash_completion_path_for, installer, join


INSTALL_NODE = [
    "mise install node@18 node@20",
    # Default version
    "mise use -g node@20",
    # Activate node corepack
    "mise exec node@18 -- corepack enable",
    "mise exec node@20 -- corepack enable",
    # Bash completions
    f"npm completion > {bash_completion_path_for('npm')}",
    f"curl -o {bash_completion_path_for('yarn')} https://raw.githubusercontent.com/dsifford/yarn-completion/master/yarn-completion.bash",
]

installer("runtimes", [Package("node", join(INSTALL_NODE))])
