#!/usr/bin/env python3

from installer import (
    Package,
    bash_completion_for,
    installer,
    join,
    write_file,
    zsh_completion_for,
)

# NOTE: this is a snippet from `npm completion` output but works fine even with `bashcompinit` in .zshrc
NPM_ZSH_COMPLETION = r"""#compdef npm

_npm() {
  local si=$IFS
  compadd -- $(COMP_CWORD=$((CURRENT-1)) \
                COMP_LINE=$BUFFER \
                COMP_POINT=0 \
                npm completion -- "${words[@]}" \
                2>/dev/null)
  IFS=$si
}

if [ "$funcstack[1]" = "_npm" ]; then
    _npm "$@"
else
    compdef _npm npm
fi
"""

INSTALL_NODE = [
    "mise install node@18 node@20",
    # Default version
    "mise use -g node@20",
    # Activate node corepack
    "mise exec node@18 -- corepack enable",
    "mise exec node@20 -- corepack enable",
    # Bash completions
    f"mise exec node@20 -- npm completion > {bash_completion_for('npm')}",
    write_file(zsh_completion_for("npm"), NPM_ZSH_COMPLETION),
    f"curl -o {bash_completion_for('yarn')} https://raw.githubusercontent.com/dsifford/yarn-completion/master/yarn-completion.bash",
    f"curl -o {zsh_completion_for('yarn')} https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/yarn/_yarn",
]

installer("runtimes", [Package("node", join(INSTALL_NODE))])
