#!/usr/bin/env python3

from installer import Package, installer, join

INSTALL_WEZTERM = [
    # This package will enable Nautilus to have "Open in WezTerm" action
    "sudo apt install -y python3-nautilus",
    'sudo dra download -i -s "wezterm-{tag}.Ubuntu22.04.deb" wez/wezterm',
    'echo "To change default terminal run: sudo update-alternatives --config x-terminal-emulator"',
]

installer(
    "terminal",
    [
        Package("wezterm", join(INSTALL_WEZTERM)),
        Package(
            "wezterm-nightly",
            "sudo dra download -t nightly -s wezterm-nightly.Ubuntu22.04.deb -i wez/wezterm",
        ),
    ],
)
