#!/usr/bin/env python3

from installer import Package, create_installer, join

INSTALL_FZF = [
    'git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf',
    '~/.fzf/install'
]

create_installer("tools", [
    # https://github.com/junegunn/fzf
    Package("fzf", join(INSTALL_FZF)),

    # https://github.com/koalaman/shellcheck
    Package("shellcheck", "sudo apt install -y shellcheck"),

    # https://github.com/tldr-pages/tldr/
    Package("tldr", "npm install -g tldr"),

    Package("aws", "pip3 install awscli --upgrade --user"),

    # https://github.com/sharkdp/bat
    Package("bat", 'sudo dra download -i -s "bat_{tag}_amd64.deb" sharkdp/bat'),

    # https://github.com/BurntSushi/ripgrep
    Package("rg", 'sudo dra download -i -s "ripgrep_{tag}_amd64.deb" BurntSushi/ripgrep'),
])()


# thefuck https://github.com/nvbn/thefuck
# pip3 install thefuck

# Joplin https://github.com/laurent22/joplin
# wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash
